name: 'rails-install'

inputs:
    ruby-version:
        required: true

runs:
    using: 'composite'

    steps:
        - name: 'Install Ruby & Rails'
          uses: 'ruby/setup-ruby@v1'
          with:
              ruby-version: '${{ inputs.ruby-version }}'
              bundler-cache: true
